version: '3'
services:

  app:
    build:
      context: .
      args:
        JDK_VERSION: 11
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/smida-test-task
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATA_MONGODB_DATABASE=smida-test-task
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
    depends_on:
      - postgres
      - mongo

  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=smida-test-task
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db

volumes:
  postgres-data:
  mongo-data: